# Generated by Django 6.0 on 2026-03-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEACHER_NAME', models.CharField(max_length=30, null=True)),
                ('TEACHER_PHONE', models.CharField(max_length=10)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECURITY_NAME', models.CharField(max_length=30, null=True)),
                ('SECURITY_PHONE', models.CharField(max_length=10)),
                ('SECURITYY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMISSION_NO', models.CharField(max_length=20, unique=True)),
                ('NAME', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=20)),
                ('YEAR', models.CharField(max_length=20)),
                ('PHONE1', models.CharField(max_length=10)),
                ('PHONE2', models.CharField(blank=True, max_length=10, null=True)),
                ('SECURITy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.security')),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEACHER_NAME', models.CharField(max_length=30, null=True)),
                ('TEACHER_PHONE', models.CharField(max_length=10)),
                ('TEACHER_DEPT', models.CharField(max_length=30, null=True)),
                ('Advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gate_Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUD_NAME', models.CharField(max_length=20)),
                ('STUD_BRANCH', models.CharField(max_length=20)),
                ('STUD_YEAR', models.CharField(max_length=20)),
                ('STUD_PHONE1', models.CharField(max_length=10)),
                ('APPORVED', models.CharField(max_length=50)),
                ('REASONS', models.CharField(max_length=50)),
                ('gate_date', models.DateField(auto_now_add=True)),
                ('gate_time', models.DateTimeField(auto_now_add=True)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.details_students')),
                ('SECURITY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.security')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='details_students',
            name='TEACHER_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.teacher'),
        ),
    ]
