# Generated by Django 6.0 on 2026-03-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_students',
            name='SECURITy',
            field=models.ForeignKey(default='W', on_delete=django.db.models.deletion.CASCADE, to='App.security'),
        ),
    ]
