# Generated by Django 6.0 on 2025-12-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMISSION_NO', models.CharField(max_length=20, unique=True)),
                ('NAME', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=20)),
                ('YEAR', models.CharField(max_length=20)),
                ('PHONE1', models.CharField(max_length=10)),
                ('PHONE2', models.CharField(blank=True, max_length=10, null=True)),
                ('TEACHER_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.teacher')),
            ],
        ),
    ]
