# Generated by Django 6.0 on 2026-03-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_details_students_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details_students',
            name='SECURITy',
        ),
    ]
