# Generated by Django 6.0 on 2026-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_details_students_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate_pass',
            name='SECURITY_ID',
        ),
        migrations.AddField(
            model_name='gate_pass',
            name='HOD_APPROVE',
            field=models.CharField(default='NO', max_length=50),
        ),
    ]
