# Generated by Django 6.0 on 2026-03-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_gate_pass_security_id_gate_pass_hod_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate_pass',
            name='gate_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Security_Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GATE_STUD_NAME', models.CharField(max_length=20)),
                ('GATE_STUD_BRANCH', models.CharField(max_length=20)),
                ('GATE_STUD_YEAR', models.CharField(max_length=20)),
                ('gate_time', models.TimeField()),
                ('re_entry', models.TimeField(blank=True, null=True)),
                ('GATE_PASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.gate_pass')),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.details_students')),
                ('TEACHER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.teacher')),
            ],
        ),
    ]
