# Generated by Django 6.0 on 2026-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_gate_pass_gate_time_security_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate_pass',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate_pass',
            name='re_enrty_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Security_Gate',
        ),
    ]
