# Generated by Django 6.0 on 2026-03-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_gate_pass_entry_time_gate_pass_re_enrty_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gate_pass',
            old_name='entry_time',
            new_name='exit_time',
        ),
    ]
